services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api
    environment:
      ENVIRONMENT: prod
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "80:80"